# Generated by Django 3.2 on 2021-12-20 10:15

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=160, verbose_name='Project Category')),
                ('slug', models.SlugField(editable=False, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=160, verbose_name='Project Name')),
                ('client', models.CharField(blank=True, max_length=100, null=True, verbose_name='Clients Name')),
                ('skills', models.CharField(blank=True, max_length=100, null=True, verbose_name='skills')),
                ('cover', models.ImageField(default='cover.png', upload_to='project/', verbose_name='Project Image')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='slug')),
                ('content', django_quill.fields.QuillField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='Published Date')),
                ('category', models.ManyToManyField(to='project.ProjectCategory')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
