# Generated by Django 3.2 on 2021-12-22 16:45

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsightCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=160, verbose_name='Insight Category')),
                ('slug', models.SlugField(editable=False, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Insight Category',
                'verbose_name_plural': 'Insight Categories',
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight', models.CharField(max_length=160, verbose_name='Insight Name')),
                ('cover', models.ImageField(default='cover.png', upload_to='Insight/', verbose_name='Insight Image')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='slug')),
                ('content', django_quill.fields.QuillField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='Published Date')),
                ('category', models.ManyToManyField(to='insight.InsightCategory')),
            ],
            options={
                'verbose_name': 'Insight',
                'verbose_name_plural': 'Insights',
            },
        ),
    ]
